# -*- coding: utf-8 -*-
"""NLP_Resume_Skill_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16yDRPOwKxoVXZtgiL7ZFxINwBwKT-iLu

Upload the dataset and extract
"""



import zipfile

zip_file = "dataset/archive (3).zip"

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall("resume_dataset")

print("Dataset extracted successfully!")

"""Load all 220 resumes"""

import os
import glob
import json
import pandas as pd

json_files = glob.glob(
    "resume_dataset/**/*.json",
    recursive=True
)

data = []

for file_path in json_files:
    with open(file_path, "r", encoding="utf-8") as file:
        resume = json.load(file)

    data.append({
        "id": resume["id"],
        "text": resume["text"],
        "skills": resume["skills"]
    })

df = pd.DataFrame(data)

print("Number of resumes:", len(df))
print("Columns:", list(df.columns))

df.head()

# Dataset skill statistics

total_skill_entries = sum(len(skills) for skills in df["skills"])

unique_skills = set()

for skills in df["skills"]:
    for skill in skills:
        unique_skills.add(skill)

print("Total skill entries:", total_skill_entries)
print("Unique skills:", len(unique_skills))

"""Text Preprocessing"""

import re

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df["clean_text"] = df["text"].apply(preprocess_text)

df[["text", "clean_text"]].head()

"""Create our Skill Vocabulary"""

# Create a unique list of all skills in the dataset

all_skills = []

for skills in df["skills"]:
    all_skills.extend(skills)

skill_vocabulary = sorted(set(all_skills))

print("Total unique skills:", len(skill_vocabulary))
print("\nFirst 20 skills:")
print(skill_vocabulary[:20])

import re

def extract_skills(text, skill_vocabulary):
    text = text.lower()
    extracted = []

    for skill in skill_vocabulary:
        skill_lower = skill.lower().strip()

        pattern = r'\b' + re.escape(skill_lower) + r'\b'

        if re.search(pattern, text):
            extracted.append(skill)

    return extracted

test_resume = df.iloc[0]

extracted_skills = extract_skills(
    test_resume["text"],
    skill_vocabulary
)

print("Resume ID:", test_resume["id"])
print("\nExtracted Skills:")
print(extracted_skills)
print("\nNumber of Skills Extracted:", len(extracted_skills))

actual_skills = set(
    skill.lower().strip()
    for skill in test_resume["skills"]
)

predicted_skills = set(
    skill.lower().strip()
    for skill in extracted_skills
)

correct_skills = actual_skills.intersection(predicted_skills)

print("Actual skills:", len(actual_skills))
print("Predicted skills:", len(predicted_skills))
print("Correctly extracted:", len(correct_skills))

print("\nCorrectly extracted skills:")
print(sorted(correct_skills))

short_skills = [
    skill for skill in skill_vocabulary
    if len(skill.strip()) <= 3
]

print("Skills with 3 or fewer characters:", len(short_skills))
print("\nExamples:")
print(short_skills[:100])

# Normalize the skill vocabulary

normalized_skills = {}

for skill in skill_vocabulary:
    key = skill.lower().strip()

    if key not in normalized_skills:
        normalized_skills[key] = skill

print("Original unique skills:", len(skill_vocabulary))
print("Normalized unique skills:", len(normalized_skills))

import re

def improved_extract_skills(text, normalized_skills):
    text = text.lower()
    extracted = []

    for skill_key, original_skill in normalized_skills.items():
        # Special handling for skills containing symbols
        if skill_key in ["c++", "c#", ".net"]:
            pattern = re.escape(skill_key)
        else:
            pattern = r"\b" + re.escape(skill_key) + r"\b"

        if re.search(pattern, text):
            extracted.append(original_skill)

    return extracted

print("Improved skill extractor created successfully!")

improved_skills = improved_extract_skills(
    test_resume["text"],
    normalized_skills
)

print("Resume ID:", test_resume["id"])

print("\nImproved Extracted Skills:")
print(improved_skills)

print("\nNumber of Skills Extracted:", len(improved_skills))

generic_skills = {
    "r",
    "it",
    "management",
    "support",
    "planning",
    "development",
    "deployment",
    "maintenance",
    "monitoring",
    "reporting",
    "responsible",
    "organized",
    "performing",
    "strategy",
    "internet",
    "software",
    "accounts",
    "payments",
    "presentation",
    "tracking",
    "manual",
    "analytics"
}

filtered_skills = {
    skill: original_skill
    for skill, original_skill in normalized_skills.items()
    if skill not in generic_skills
}

print("Before filtering:", len(normalized_skills))
print("After filtering:", len(filtered_skills))

def final_extract_skills(text, filtered_skills):
    text = text.lower()
    extracted = []

    for skill_key, original_skill in filtered_skills.items():

        if skill_key in ["c++", "c#", ".net"]:
            pattern = re.escape(skill_key)
        else:
            pattern = r"\b" + re.escape(skill_key) + r"\b"

        if re.search(pattern, text):
            extracted.append(original_skill)

    return extracted

print("Final skill extractor created successfully!")

final_skills = final_extract_skills(
    test_resume["text"],
    filtered_skills
)

print("Resume ID:", test_resume["id"])

print("\nFinal Extracted Skills:")
print(final_skills)

print("\nNumber of Skills Extracted:", len(final_skills))

actual_skills = set(
    skill.lower().strip()
    for skill in test_resume["skills"]
)

predicted_skills = set(
    skill.lower().strip()
    for skill in final_skills
)

correct_skills = actual_skills.intersection(predicted_skills)

true_positive = len(correct_skills)
false_positive = len(predicted_skills - actual_skills)
false_negative = len(actual_skills - predicted_skills)

precision = true_positive / (true_positive + false_positive)
recall = true_positive / (true_positive + false_negative)

if precision + recall > 0:
    f1_score = 2 * (precision * recall) / (precision + recall)
else:
    f1_score = 0

print("True Positives:", true_positive)
print("False Positives:", false_positive)
print("False Negatives:", false_negative)

print("\nPrecision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("F1-score:", round(f1_score, 4))

false_negatives = sorted(actual_skills - predicted_skills)

print("Number of missed skills:", len(false_negatives))
print("\nFirst 50 missed skills:")
print(false_negatives[:50])

import sklearn

print("scikit-learn version:", sklearn.__version__)

total_tp = 0
total_fp = 0
total_fn = 0

for _, row in df.iterrows():

    predicted = set(
        skill.lower().strip()
        for skill in final_extract_skills(
            row["text"],
            filtered_skills
        )
    )

    actual = set(
        skill.lower().strip()
        for skill in row["skills"]
    )

    total_tp += len(predicted & actual)
    total_fp += len(predicted - actual)
    total_fn += len(actual - predicted)

precision = total_tp / (total_tp + total_fp)
recall = total_tp / (total_tp + total_fn)
f1 = 2 * precision * recall / (precision + recall)

print("Total True Positives:", total_tp)
print("Total False Positives:", total_fp)
print("Total False Negatives:", total_fn)

print("\nOverall Precision:", round(precision, 4))
print("Overall Recall:", round(recall, 4))
print("Overall F1-score:", round(f1, 4))

df["extracted_skills"] = df["text"].apply(
    lambda text: final_extract_skills(
        text,
        filtered_skills
    )
)

print("Skill extraction completed for all resumes!")
print(df[["id", "extracted_skills"]].head())

resume_id = 219

result = df[df["id"] == resume_id].iloc[0]

print("Resume ID:", result["id"])
print("Number of extracted skills:", len(result["extracted_skills"]))

print("\nExtracted Skills:")
for skill in result["extracted_skills"]:
    print("-", skill)

"""Make a simple resume input system"""

resume_id = int(input("Enter Resume ID: "))

result = df[df["id"] == resume_id]

if len(result) == 0:
    print("Resume ID not found.")
else:
    result = result.iloc[0]

    print("\nResume ID:", result["id"])
    print("Number of extracted skills:", len(result["extracted_skills"]))

    print("\nExtracted Skills:")
    for skill in result["extracted_skills"]:
        print("-", skill)

resume_id = 137

result = df[df["id"] == resume_id].iloc[0]

actual = set(skill.lower().strip() for skill in result["skills"])
predicted = set(skill.lower().strip() for skill in result["extracted_skills"])

print("Resume ID:", resume_id)
print("Actual skills:", len(actual))
print("Extracted skills:", len(predicted))

print("\n--- ACTUAL SKILLS ---")
for skill in sorted(actual):
    print("-", skill)

print("\n--- EXTRACTED SKILLS ---")
for skill in sorted(predicted):
    print("-", skill)

print("\n--- MISSED SKILLS ---")
for skill in sorted(actual - predicted):
    print("-", skill)

df["actual_skill_count"] = df["skills"].apply(len)
df["extracted_skill_count"] = df["extracted_skills"].apply(len)

results_df = df[
    ["id", "actual_skill_count", "extracted_skill_count"]
]

results_df.head(10)

print("Average actual skills:",
      round(df["actual_skill_count"].mean(), 2))

print("Average extracted skills:",
      round(df["extracted_skill_count"].mean(), 2))

print("Maximum actual skills:",
      df["actual_skill_count"].max())

print("Maximum extracted skills:",
      df["extracted_skill_count"].max())

import matplotlib.pyplot as plt

labels = ["Actual Skills", "Extracted Skills"]
values = [
    df["actual_skill_count"].mean(),
    df["extracted_skill_count"].mean()
]

plt.figure(figsize=(7, 5))
plt.bar(labels, values)

plt.title("Average Actual vs Extracted Skills")
plt.ylabel("Number of Skills")
plt.show()

metrics = ["Precision", "Recall", "F1-score"]
values = [precision, recall, f1]

plt.figure(figsize=(7, 5))
plt.bar(metrics, values)

plt.title("Resume Skill Extraction Performance")
plt.ylabel("Score")
plt.ylim(0, 1)

plt.show()

resume_id = int(input("Enter Resume ID: "))

result = df[df["id"] == resume_id]

if len(result) == 0:
    print("Resume ID not found.")

else:
    result = result.iloc[0]

    print("\n===================================")
    print("       RESUME SKILL EXTRACTOR")
    print("===================================")

    print("\nResume ID:", result["id"])
    print("Skills Found:", len(result["extracted_skills"]))

    print("\nExtracted Skills:")
    print("-----------------------------------")

    for i, skill in enumerate(result["extracted_skills"], 1):
        print(f"{i}. {skill}")

output_df = df[[
    "id",
    "text",
    "skills",
    "extracted_skills"
]].copy()

output_df.to_csv(
    "resume_skill_extraction_results.csv",
    index=False
)

print("Results saved successfully!")
print("File: resume_skill_extraction_results.csv")

print("===== RESUME SKILL EXTRACTION PROJECT =====")

print("\nDataset:")
print("Number of resumes:", len(df))

print("\nSkill Statistics:")
print("Average actual skills:", round(df["actual_skill_count"].mean(), 2))
print("Average extracted skills:", round(df["extracted_skill_count"].mean(), 2))

print("\nEvaluation:")
print("Precision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("F1-score:", round(f1, 4))

